Repository Pro-Folio/23-W-Cow-Project-Frontend, pull requests merged in 2023-02, with the labels that each got.

#2 feat : 회원가입 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/component/Header.jsx
  src/pages/Join.jsx
  src/pages/Main.jsx
  src/reportWebVitals.js
Labels: enhancement

#5 Feat : My 페이지 퍼블리싱 구현, Design : Write 페이지 이미지 입력 칸 디자인 변경
  src/pages/My.jsx
  src/pages/Write.jsx
Labels: Feat

#6 Feat: 중복 여부에 따른 helper text
  .eslintrc.json
  src/pages/Join.jsx
Labels: Feat

#9 Style : My page에서 Information component 분리
  src/App.js
  src/component/Board.jsx
  src/component/Information.jsx
  src/pages/Write.jsx
Labels: Style

#12 Refactor : Write 페이지 리팩토링
  .eslintrc.json
  .prettierrc.js
  package-lock.json
  package.json
  src/App.js
  src/component/Information.jsx
  src/index.js
  src/pages/Write.jsx
  src/reportWebVitals.js
Labels: Refactor

#11 Style: isNameSame 변수명 변경
  src/pages/Join.jsx
Labels: Style

#13 Refactor : Information component 분리
  src/pages/My.jsx
Labels: Refactor

#15 Style : stacks import
  src/pages/Join.jsx
Labels: Style

#16 Refactor : 로그인 회원가입 컴포넌트화
  .eslintrc.json
  src/App.js
  src/component/Join.jsx
  src/pages/Join.jsx
  src/pages/Sign.jsx
Labels: Refactor

#17 Feat: Board Component
  .github/ISSUE_TEMPLATE/-bug-.md
  src/component/Board.jsx
  src/component/Information.jsx
  src/component/Stack.jsx
  src/helper/types.js
  src/pages/Detail.jsx
  src/pages/Main.jsx
  src/pages/My.jsx
  src/pages/Write.jsx
Labels: Feat

#19 Feat: Board 수정 및 삭제
  src/component/Board.jsx
  src/helper/types.js
  src/index.css
  src/pages/My.jsx
Labels: Feat

#20 Design : 로그인 페이지 레이아웃 구현
  src/component/Sign.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
Labels: Design

#21 Design : image 아이콘 추가
  src/component/Board.jsx
  src/img/BsImage.png
  src/pages/My.jsx
  src/pages/Write.jsx
Labels: Design

#22 Feat: 로그인 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/img/hidePW.png
  src/img/showPW.png
  src/index.js
  src/pages/Join.jsx
  src/pages/Login.jsx
Labels: Feat

#23 Feat : 작성페이지 달력 구현
  package-lock.json
  package.json
  src/pages/Write.jsx
Labels: Feat

#24 Feat : 로그인 cookie -> local storage
  package-lock.json
  package.json
  src/App.js
  src/component/Header.jsx
  src/pages/Login.jsx
Labels: Feat

#25 Feat : 헤더 로그인 로그아웃 구현
  package-lock.json
  package.json
  src/component/Header.jsx
  src/component/Sign.jsx
  src/pages/Join.jsx
Labels: Feat

#27 Feat : required 기능 추가
  package-lock.json
  package.json
  src/index.css
  src/pages/Write.jsx
Labels: Feat

#28 Design: box hover 추가
  src/component/Board.jsx
  src/pages/Main.jsx
  src/pages/My.jsx
Labels: Design

#29 Refactor: 헤더 url이동 navigate로 변경
  src/App.js
  src/component/Header.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/Write.jsx
Labels: Refactor

#31 Feat : 헤더 검색 기능 구현
  src/App.js
  src/component/Header.jsx
  src/index.js
  src/pages/Join.jsx
Labels: Feat

#32 Feat : 작성페이지 이미지 업로드 및 미리보기 기능 구현
  src/App.js
  src/pages/Write.jsx
Labels: Feat

#34 chore : cors 오류 수정
  package.json
  src/App.js
  src/component/Header.jsx
  src/index.js
  src/pages/Join.jsx
  src/pages/Login.jsx
Labels: Fix

#35 Fix : 등록 버튼 클릭시 submit 오류 해결
  src/pages/Write.jsx
Labels: Fix

#38 Fix: 작성페이지 img 수정중
  src/pages/Write.jsx
Labels: Fix

#42 Fix : stack 오류 수정
  src/component/Header.jsx
  src/img/pofolLogo.png
  src/pages/Write.jsx
Labels: Fix

#44 Fix : 렌더링 수정
  src/App.js
  src/component/Board.jsx
  src/pages/Detail.jsx
  src/pages/Main.jsx
  src/pages/My.jsx
  src/pages/Write.jsx
Labels: Fix

#46 Fix : 렌더링 오류 수정
  src/App.js
  src/component/Board.jsx
  src/pages/Main.jsx
  src/pages/My.jsx
Labels: Fix

#47 Fix: api error수정
  src/api/portfolio.jsx
  src/index.js
  src/pages/Write.jsx
Labels: Fix

#48 Style : url 변경
  src/App.js
  src/component/Board.jsx
Labels: Style

#49 Feat : WriteBoard 추가 컴포넌트 구현
  src/component/Information.jsx
  src/component/WriteBoard.jsx
  src/pages/My.jsx
Labels: Feat

#50 Feat : 날짜 시작일/ 종료일 validate 설정
  src/pages/Write.jsx
Labels: Feat

#51 Fix: board에서 stack 노출
  package-lock.json
  package.json
  src/App.js
  src/api/portfolio.jsx
  src/component/Board.jsx
  src/component/Header.jsx
  src/helper/cookie.js
  src/helper/style.js
  src/img/LOGO.png
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/My.jsx
Labels: Fix

#54 Feat : 작성 페이지 유효성 검사 및 이미지 업로드 아이콘 추가
  src/component/Header.jsx
  src/component/WriteBoard.jsx
  src/pages/Write.jsx
Labels: Feat

#55 Fix : authorization default 값 제거
  src/pages/Login.jsx
Labels: Fix

#56 Fix: my 페이지 렌더링 오류 수정
  src/component/Board.jsx
  src/pages/My.jsx
Labels: Fix

#57 Design : stack 변수명, 색 변경
  src/helper/types.js
Labels: Design

#58 Design : 이미지 크기 고정 및 보드크기 수정
  src/component/Board.jsx
  src/pages/Detail.jsx
  src/pages/Write.jsx
Labels: Design

#60 Fix: stack text-> component
  src/api/portfolio.jsx
  src/component/Board.jsx
  src/component/Information.jsx
  src/component/WriteBoard.jsx
  src/pages/Detail.jsx
  src/pages/Login.jsx
  src/pages/My.jsx
  src/pages/Write.jsx
Labels: Fix

#61 Fix: writepage image
  src/api/portfolio.jsx
  src/component/WriteBoard.jsx
  src/pages/Write.jsx
Labels: Fix

#62 Style : logo명 변경
  src/component/Header.jsx
Labels: Style

#64 Design : 상세페이지 레이아웃 변경
  src/pages/Detail.jsx
  src/pages/Write.jsx
Labels: Design

#65 Design : 이미지 크기 변경 및 아이콘 추가
  src/pages/Write.jsx
Labels: Design

#66 Refactor : 로그인 회원가입 리팩토링
  src/App.js
  src/helper/types.js
  src/pages/Join.jsx
  src/pages/Login.jsx
Labels: Refactor

#67 Fix : stacks 색상 추가 및 변수명 변경
  src/helper/types.js
  src/pages/Write.jsx
Labels: Fix

#69 Design : 작성페이지 반응형
  src/index.css
  src/pages/Write.jsx
Labels: Design

#71 Design : 로그인 회원가입 반응형 구현
  src/component/Header.jsx
  src/component/Sign.jsx
  src/helper/style.js
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
Labels: Design

#72 Style : border 제거
  src/component/Sign.jsx
  src/pages/Join.jsx
Labels: Style

#73 Fix : 자동완성 제거
  src/pages/Login.jsx
Labels: Fix
